//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Constantes {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Constantes.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao executar o método..
        /// </summary>
        public static string ERRO_EXEC_METODO {
            get {
                return ResourceManager.GetString("ERRO_EXEC_METODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao executar consulta no repositorio..
        /// </summary>
        public static string ERRO_REPOSITORIO {
            get {
                return ResourceManager.GetString("ERRO_REPOSITORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 845B6345-C8BA-4896-9EC9-FBD55974CC43.
        /// </summary>
        public static string ORIGEM_CADASTRO_INDICACAO {
            get {
                return ResourceManager.GetString("ORIGEM_CADASTRO_INDICACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 34918148-8CDC-4621-B7F1-0D7C7F0BCF29.
        /// </summary>
        public static string SENHA_CHAVE {
            get {
                return ResourceManager.GetString("SENHA_CHAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 934CC63A-2967-4B11-B424-705818CCF94A.
        /// </summary>
        public static string STATUS_APROVADO {
            get {
                return ResourceManager.GetString("STATUS_APROVADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 63DCBE44-E538-4580-8130-901F8CC282B3.
        /// </summary>
        public static string STATUS_PENDENTE {
            get {
                return ResourceManager.GetString("STATUS_PENDENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3E9FB455-1BDA-4C02-B398-D9607FAB836B.
        /// </summary>
        public static string STATUS_REPROVADO {
            get {
                return ResourceManager.GetString("STATUS_REPROVADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FABIO MERLI MEMBERSHIP.
        /// </summary>
        public static string TITULO_EMAIL_APROVACAO {
            get {
                return ResourceManager.GetString("TITULO_EMAIL_APROVACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FABIO MERLI MEMBERSHIP: PASSWORD RESET.
        /// </summary>
        public static string TITULO_EMAIL_RESET_SENHA {
            get {
                return ResourceManager.GetString("TITULO_EMAIL_RESET_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid e-mail or password.
        /// </summary>
        public static string USUARIO_NAO_AUTORIZADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_AUTORIZADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado.
        /// </summary>
        public static string USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }

        public static string USUARIO_EMAIL_NULL
        {
            get
            {
                return ResourceManager.GetString("USUARIO_EMAIL_NULL", resourceCulture);
            }
        }

        public static string SUCCESS
        {
            get
            {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }

        public static string WARNING
        {
            get
            {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }

        public static string DANGER
        {
            get
            {
                return ResourceManager.GetString("DANGER", resourceCulture);
            }
        }

        public static string USUARIO_AUTORIZADO
        {
            get
            {
                return ResourceManager.GetString("USUARIO_AUTORIZADO", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao executar consulta no repositorio..
        /// </summary>
        public static string ERRO_CONSULTA
        {
            get
            {
                return ResourceManager.GetString("ERRO_CONSULTA", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante..
        /// </summary>
        public static string ATUALIZADO_SUCESSO
        {
            get
            {
                return ResourceManager.GetString("ATUALIZADO_SUCESSO", resourceCulture);
            }
        }

        public static string INCLUIDO_SUCESSO
        {
            get
            {
                return ResourceManager.GetString("INCLUIDO_SUCESSO", resourceCulture);
            }
        }

        public static string INATIVADO_SUCESSO
        {
            get
            {
                return ResourceManager.GetString("INATIVADO_SUCESSO", resourceCulture);
            }
        }

        public static string REGISTRO_NAO_ENCONTRADO
        {
            get
            {
                return ResourceManager.GetString("REGISTRO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        public static string MASTER
        {
            get
            {
                return ResourceManager.GetString("MASTER", resourceCulture);
            }
        }

        public static string DESENVOLVEDOR
        {
            get
            {
                return ResourceManager.GetString("DESENVOLVEDOR", resourceCulture);
            }
        }
        public static string PERFIL_NIVEL_BAIXO
        {
            get
            {
                return ResourceManager.GetString("PERFIL_NIVEL_BAIXO", resourceCulture);
            }
        }

        public static string EMAIL_EXISTE
        {
            get
            {
                return ResourceManager.GetString("EMAIL_EXISTE", resourceCulture);
            }
        }

        public static string CAMPO_INVALIDO
        {
            get
            {
                return ResourceManager.GetString("CAMPO_INVALIDO", resourceCulture);
            }
        }

        public static string SENHAS_NAO_COINCIDEM
        {
            get
            {
                return ResourceManager.GetString("SENHAS_NAO_COINCIDEM", resourceCulture);
            }
        }

        public static string DESCRICAO_EXISTE
        {
            get
            {
                return ResourceManager.GetString("DESCRICAO_EXISTE", resourceCulture);
            }
        }

        public static string EXCLUIDO_SUCESSO
        {
            get
            {
                return ResourceManager.GetString("EXCLUIDO_SUCESSO", resourceCulture);
            }
        }

        public static int STATUS_OK
		{
            get
            {
                return Convert.ToInt32(ResourceManager.GetString("STATUS_OK", resourceCulture));
            }
        }

        public static int STATUS_CONFLICT
		{
            get
            {
                return Convert.ToInt32(ResourceManager.GetString("STATUS_CONFLICT", resourceCulture));
            }
        }

        public static int STATUS_UNAUTHORIZED
		{
            get
            {
                return Convert.ToInt32(ResourceManager.GetString("STATUS_UNAUTHORIZED", resourceCulture));
            }
        }

        public static int STATUS_BAD_REQUEST
		{
            get
            {
                return Convert.ToInt32(ResourceManager.GetString("STATUS_BAD_REQUEST", resourceCulture));
            }
        }

        public static int STATUS_NOT_FOUND
		{
            get
            {
                return Convert.ToInt32(ResourceManager.GetString("STATUS_NOT_FOUND", resourceCulture));
            }
        }

        public static string BUSCA_SUCESSO
		{
            get
            {
                return ResourceManager.GetString("BUSCA_SUCESSO", resourceCulture);
            }
        }

        public static string DELETE_SUCESSO
		{
            get
            {
                return ResourceManager.GetString("DELETE_SUCESSO", resourceCulture);
            }
        }
    }
}
